DROP database ejercicio2;

CREATE DATABASE IF NOT EXISTS ejercicio2;

USE ejercicio2;

CREATE TABLE IF NOT EXISTS empresa(
cif VARCHAR(9) NOT NULL PRIMARY KEY,
nombre VARCHAR(50) NOT NULL,
telefono INTEGER UNSIGNED NOT NULL,
direccion VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS alumno(
dni VARCHAR(9) NOT NULL PRIMARY KEY,
cif VARCHAR(9) NOT NULL,
nombre VARCHAR(50) NOT NULL,
direccion VARCHAR(100) NOT NULL,
telelfono INTEGER NOT NULL,
edad TINYINT UNSIGNED NOT NULL,
FOREIGN KEY (cif) REFERENCES empresa(cif) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS profesor(
dni VARCHAR(9) NOT NULL PRIMARY KEY,
nombre VARCHAR(50) NOT NULL,
apellido VARCHAR(50) NOT NULL,
direccion VARCHAR(100) NOT NULL,
telelfono INTEGER UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS curso(
codigo INTEGER UNSIGNED NOT NULL PRIMARY KEY,
programa VARCHAR(10000) NOT NULL,
duracion SMALLINT UNSIGNED NOT NULL,
titulo VARCHAR(100) NOT NULL,
fechainicio DATE NOT NULL,
fechafin DATE NOT NULL,
numerocurso TINYINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS realizar(
dni VARCHAR(9) NOT NULL,
codigo INTEGER UNSIGNED NOT NULL,
nota SMALLINT NOT NULL,
PRIMARY KEY (dni, codigo),
FOREIGN KEY (dni) REFERENCES alumno(dni) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (codigo) REFERENCES curso(codigo) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS impartir(
codigo INTEGER UNSIGNED NOT NULL,
dni VARCHAR(9) NOT NULL,
PRIMARY KEY (codigo,dni),
FOREIGN KEY (codigo) REFERENCES curso(codigo) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (dni) REFERENCES profesor(dni) ON DELETE CASCADE ON UPDATE CASCADE
);
