DROP database IF EXISTS ejercicio8;

CREATE DATABASE IF NOT EXISTS ejercicio8;

USE ejercicio8;

CREATE TABLE IF NOT EXISTS aeropuerto(
idaeropuerto INTEGER UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
localidad VARCHAR(100) NOT NULL,
pais VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS avion(
idavion INTEGER UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
numplazas INTEGER UNSIGNED NOT NULL,
idaeropuerto INTEGER UNSIGNED NOT NULL,
FOREIGN KEY (idaeropuerto) REFERENCES aeropuerto(idaeropuerto) ON DELETE CASCADE ON UPDATE CASCADE
);





CREATE TABLE IF NOT EXISTS vuelo(
idvuelo INTEGER UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
fechasalida DATETIME NOT NULL,
fechallegada DATETIME NOT NULL,
aeropuertosalida INTEGER UNSIGNED NOT NULL,
aeropuertodestino INTEGER UNSIGNED NOT NULL,
idavion INTEGER UNSIGNED NOT NULL,
FOREIGN KEY (idavion) REFERENCES avion(idavion) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS tarjetaembarque(
idembarque INTEGER UNSIGNED NOT NULL PRIMARY KEY
);


CREATE TABLE IF NOT EXISTS asiento(
fila INTEGER UNSIGNED NOT NULL,
columna VARCHAR(2) NOT NULL,
planta VARCHAR(2) NOT NULL,
idembarque INTEGER UNSIGNED NOT NULL,
PRIMARY KEY (fila,columna,planta),
KEY idx_columna(columna),
FOREIGN KEY (idembarque) REFERENCES tarjetaembarque(idembarque) ON DELETE CASCADE ON UPDATE CASCADE
);



CREATE TABLE IF NOT EXISTS cliente(
idcliente INTEGER UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
dni INTEGER UNSIGNED NOT NULL,
nombre VARCHAR(100) NOT NULL,
direccion VARCHAR(100) NOT NULL,
telefono INTEGER UNSIGNED NOT NULL,
tarjetacredito INTEGER UNSIGNED NOT NULL,
idembarque INTEGER UNSIGNED NOT NULL,
FOREIGN KEY (idembarque) REFERENCES tarjetaembarque(idembarque) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS reserva(
idreserva INTEGER UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
numeroplazas SMALLINT UNSIGNED NOT NULL,
fechallegada DATETIME NOT NULL,
idcliente INTEGER UNSIGNED NOT NULL,
idembarque INTEGER UNSIGNED NOT NULL,
FOREIGN KEY (idcliente) REFERENCES cliente(idcliente) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (idembarque) REFERENCES tarjetaembarque(idembarque) ON DELETE CASCADE ON UPDATE CASCADE
);
